# Generated by Django 3.2.10 on 2021-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.TextField(default='')),
                ('msg', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.CharField(default='', max_length=200)),
                ('image', models.FileField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=200)),
                ('password', models.TextField(default='')),
            ],
        ),
    ]
