# Generated by Django 4.0 on 2021-12-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_tb',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
