# Generated by Django 4.0 on 2021-12-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_register_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_tb',
            name='status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
