# Generated by Django 4.0 on 2022-01-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_admin_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_tb',
            name='password',
        ),
        migrations.RemoveField(
            model_name='contact_tb',
            name='phone',
        ),
        migrations.AddField(
            model_name='register_tb',
            name='hpassword',
            field=models.TextField(default=''),
        ),
    ]
