# Generated by Django 4.0 on 2022-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_contact_tb_password_remove_contact_tb_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
