# Generated by Django 4.0 on 2022-01-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.CharField(default='n', max_length=200),
        ),
    ]
