# Generated by Django 4.0 on 2022-01-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_product_tb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_tb',
            name='date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
