# Generated by Django 4.0 on 2022-01-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_payment_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_tb',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
